apiVersion: v1
kind: Namespace
metadata:
  name: vectorsmuggle
  labels:
    name: vectorsmuggle
    app: vectorsmuggle
    environment: production
    security.istio.io/tlsMode: istio
  annotations:
    description: "VectorSmuggle proof-of-concept namespace"
    contact: "security-research@example.com"
spec:
  finalizers:
  - kubernetes

---
apiVersion: v1
kind: LimitRange
metadata:
  name: vectorsmuggle-limits
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: resource-limits
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "4000m"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vectorsmuggle-quota
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: resource-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    requests.storage: "100Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"