apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectorsmuggle-data-pvc
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectorsmuggle-cache-pvc
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectorsmuggle-logs-pvc
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-pvc
  namespace: vectorsmuggle
  labels:
    app: qdrant
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd