apiVersion: v1
kind: ServiceAccount
metadata:
  name: vectorsmuggle
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vectorsmuggle-role
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vectorsmuggle-rolebinding
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: rbac
subjects:
- kind: ServiceAccount
  name: vectorsmuggle
  namespace: vectorsmuggle
roleRef:
  kind: Role
  name: vectorsmuggle-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qdrant
  namespace: vectorsmuggle
  labels:
    app: qdrant
    component: rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qdrant-role
  namespace: vectorsmuggle
  labels:
    app: qdrant
    component: rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qdrant-rolebinding
  namespace: vectorsmuggle
  labels:
    app: qdrant
    component: rbac
subjects:
- kind: ServiceAccount
  name: qdrant
  namespace: vectorsmuggle
roleRef:
  kind: Role
  name: qdrant-role
  apiGroup: rbac.authorization.k8s.io