apiVersion: v1
kind: Secret
metadata:
  name: vectorsmuggle-secrets
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: secrets
type: Opaque
data:
  # Base64 encoded OpenAI API key (replace with actual key)
  # Example: echo -n "sk-your-openai-api-key" | base64
  openai-api-key: c2stcGxhY2Vob2xkZXItb3BlbmFpLWFwaS1rZXk=
  
  # Base64 encoded Pinecone API key (if using Pinecone)
  # Example: echo -n "your-pinecone-api-key" | base64
  pinecone-api-key: cGxhY2Vob2xkZXItcGluZWNvbmUtYXBpLWtleQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: vectorsmuggle-internal-docs
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: sensitive-data
type: Opaque
data:
  # Base64 encoded sensitive documents
  # These would contain the actual internal documents for testing
  # Example: cat strategic_roadmap.pdf | base64 -w 0
  strategic_roadmap.pdf: UERGIGZpbGUgY29udGVudCB3b3VsZCBnbyBoZXJlIGFzIGJhc2U2NCBlbmNvZGVk

---
apiVersion: v1
kind: Secret
metadata:
  name: vectorsmuggle-tls
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Generate with: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLiBZb3VyIFRMUyBjZXJ0aWZpY2F0ZSBoZXJlIC4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLiBZb3VyIFRMUyBwcml2YXRlIGtleSBoZXJlIC4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t

---
apiVersion: v1
kind: Secret
metadata:
  name: vectorsmuggle-registry
  namespace: vectorsmuggle
  labels:
    app: vectorsmuggle
    component: registry-auth
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker registry credentials
  # Example: echo -n '{"auths":{"registry.example.com":{"username":"user","password":"pass","auth":"dXNlcjpwYXNz"}}}' | base64
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==